name: Deploy Github

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.16.2]

    steps:
      # 1.检出仓库
      - name: Checkout
        uses: actions/checkout@v2

      # # 2. 设置pnpm包管理器
      # - name: Install npm
      #   uses: pnpm/action-setup@v2.0.1
      #   with:
      #     version: 6.15.1

      # 3. 安装nodejs
      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "npm" # 缓存


      # 4.安装依赖
      - name: Install deps
        run: |
          npm config set registry https://registry.npm.taobao.org
          npm i hexo-cli -g
          npm install

      # 5.构建/部署
      - name: Deploy
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
        run: bash ./run.sh
