name: Deploy Github

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]

    steps:
      # 1.检出仓库
      - name: Checkout
        uses: actions/checkout@v2

      # 2. 初始化和更新子模块
      - name: Update Submodules
        run: git submodule update --init --recursive

      # 3.设置hugo环境
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.132.1'

      # 4.设置node环境
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      # 5. 构建/部署
      - name: Deploy
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
        run: |
          cd hugoWithLoveIt
          bash ./run.sh
