name: Deploy Github

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x]

    steps:
      # 1.检出仓库
      - name: Checkout
        uses: actions/checkout@v2

      # 2.设置hugo环境
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'



      # 构建/部署
      - name: Deploy
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
        run: |
          cd hugoWithLoveIt
          bash ./run.sh
